### ISSUE TITLE
[wanted] there is issue on check word in english

### ISSUE THREAD

**Issue by sinakit** [ZhelinCheng/mint-filter#193]
**Problem**
- It is not support lower or upper case sensitive

**Scenario**
- I want to replace keyword `hello` to with `*****`
- If I pass `hello, my name is`, It will convert to `*****, my name is` [Correct]
- if I pass `Hello, my name is`, It will convert to `Hello, my name is` [Need help]
- if I pass `Hello, my name is`, It will convert to `*****, my name is` [Wanted]

- Tested image
<img width="793" alt="Screen Shot 2021-12-22 at 2 52 18 PM" src="https://user-images.githubusercontent.com/78096556/147055913-6d7831e9-1d8e-4ac8-98e7-2a4c60a565fc.png">
- Result image
<img width="407" alt="Screen Shot 2021-12-22 at 2 53 34 PM" src="https://user-images.githubusercontent.com/78096556/147056061-fe2087ea-feb7-4a42-8065-d2677c698cb0.png">

**Comment by ZhelinCheng** [comment]
options: transform

**Comment by sinakit** [comment]
Thank you for your assisting. It is working fine.
