### ISSUE TITLE
TypeError: Mint is not a constructor

### ISSUE THREAD

**Issue by SchneeHertz** [ZhelinCheng/mint-filter#195]
使用Commonjs的require导入和ESM的await import导入都有这个问题
我看到有Closed的issue提到这个问题，但这个问题似乎没有被修复
使用的版本是4.0.1-beta

**Comment by SchneeHertz** [comment]
const Mint = await import('mint-filter')
mint = new Mint.default.default(sensitiveWordList)

这样写可以用，但还是希望能修复这个问题

**Comment by ZhelinCheng** [comment]
试试新版本，并使用
```
const { Mint } = require('mint-filter')
```

**Comment by SchneeHertz** [comment]
@ZhelinCheng 我安装了4.0.2-beta后可以用require了，使用也没有问题，谢谢。
