### ISSUE TITLE
建议增加对低版本node支持【项目中使用了Object.values】

### ISSUE THREAD

**Issue by zzl09** [ZhelinCheng/mint-filter#2]
感谢共享这个好模块，赞一个！
由于使用了Object.values，低版本node会报错，推荐加入支持
![image](https://user-images.githubusercontent.com/5655049/63571680-77214e00-c5b3-11e9-81a7-b50603eebcc2.png)

目前已引入的项目中使用如下hack方法解决
`if (!Object['values']) Object['values'] = o => Object.keys(o).map(k => o[k]);`

**Comment by ZhelinCheng** [comment]
@zzl09 感谢你的反馈，我将会在周末加入对Object.values的低版本支持。但该项目使用了特别多的新特性。建议Node>=7.6。

**Comment by zzl09** [comment]
@ZhelinCheng 好的，再次感谢😁

**Comment by ZhelinCheng** [comment]
@zzl09 已经上传了1.1.6版本的包，做了该方法的兼容。Node的调用方式稍微修改了。
<=1.1.5版本的调用方式：
```
const Mint = require('mint-filter')
```

>=1.1.6版本的调用方式：
```
const Mint = require('mint-filter').default
```
