### ISSUE TITLE
可以加上自定义替换字符吗

### ISSUE THREAD

**Issue by SchneeHertz** [ZhelinCheng/mint-filter#201]
现在匹配到的词会替换为*，可以增加一个参数，让匹配到的词替换为其他字符吗

**Comment by ZhelinCheng** [comment]
你是想在过滤时增加一个参数，传递敏感词:替换词的映射吗？还是在实例化的时候

**Comment by SchneeHertz** [comment]
实例化的时候就可以，不需要映射，所有的敏感词都替换成自定义的那个字符

**Comment by ZhelinCheng** [comment]
发了，你可以试试，实例化传递第二个参数，可以看看我的单元测试

**Comment by SchneeHertz** [comment]
我试了没问题，谢谢。
