### ISSUE TITLE
`Mint` 单例问题

### ISSUE THREAD

**Issue by SethWen** [ZhelinCheng/mint-filter#3]
您好，今天尝试您这个库，发现在 `new Mint()` 的时候， 得到的是一个单例对象，建议把这个单例去掉， 原因如下：
1. 这个单例从 API 角度看， 完全看不出来，让人很迷惑;
2. 如果是单例的话， 当一个服务中需要多个互不干扰的 filter 的时候，目前看起来没法实现。

**Comment by ZhelinCheng** [comment]
@SethWen 好的，之前选择单例是我忽略了第二点这种情况，待会我会去掉。

**Comment by ZhelinCheng** [comment]
@SethWen 已经处理了，1.1.8版本

**Comment by SethWen** [comment]
多谢～
