### ISSUE TITLE
new Mint 不支持传入空数组

### ISSUE THREAD

**Issue by XHMM** [ZhelinCheng/mint-filter#44]
在使用时，由于需要动态传入敏感词数组，所以数组可能为空数组，但源码中new Mint要求长度必须大于1，希望添加对传入空数组的支持。

**Comment by ZhelinCheng** [comment]
动态传入？是可能存在多次传入，还是说只会有后面一次传入的可能？因为目前没有动态添加的方法，所以提供这么两个解决临时解决方案，后期会添加相关方法：

方案一：
```
// 全局的变量
const mint = null;

// 第一次传入
mint = new Mint(['A'])

// 第二次传入
mint = new Mint(['A', 'B'])
```
方案二（这个我没有试，但按道理是OK的）：
```
const mint = null;

// 第一次传入
mint = new Mint(['A'])

// 第二次传入
mint.insert('B')

// 重新更新Failure表
mint.createFailureTable()
```

**Comment by XHMM** [comment]
因为获取的数据可能为空，所以第一次传入的值有可能是空数组： `mint=new Mint([])`，但源码里不支持数组长度小于1的情况,于是会报错。

不过我后来修改了自己的代码逻辑，当数组为空时就不构造Mint了。

但我觉得还是得在文档说明下不能传入空数组，或是修改下源码对空数组的处理，否则使用者确实不知道空数组还会导致报错  (还好我的代码有测试，不然直接放线上就gg了😂)

**Comment by ZhelinCheng** [comment]
因为大多需求可能是在程序启动时获取敏感词并进行实例化，所以选择直接抛出错误，给出原因，但正如你所描述的情况，这样可能有点过于强硬，不够弹性，会在下一个版本进行调整。

**Comment by ZhelinCheng** [comment]
在2.0.6版本中已经修复，可以传递空数组了。

**Comment by ZhelinCheng** [comment]
@XHMM  刚刚更新了新的搜索方法，更快也更准确，建议升级到最新版本。

**Comment by XHMM** [comment]
thanks ! 🥰
