### ISSUE TITLE
好像返回值里面的word拼错了

### ISSUE THREAD

**Issue by hidamarink** [ZhelinCheng/mint-filter#97]
![image](https://user-images.githubusercontent.com/16144634/83723142-c632fe00-a670-11ea-8094-013f666e8eb3.png)
![image](https://user-images.githubusercontent.com/16144634/83723606-8ae4ff00-a671-11ea-939c-a024418769d6.png)

**Comment by ZhelinCheng** [comment]
感谢反馈，在3.0.1中已修复。
